### PR TITLE
add headers, fix typos

### PR DESCRIPTION
**Pull request by Tocic**

### CODE REVIEW

**Comment by GeertLitjens** [comment]
I'm unsure why these includes are needed, not of the platforms I currently compile ASAP on require this include. Can you explain why you think they are needed?

**Comment by Tocic** [comment]
I couldn't compile the project without those headers with my implementation. Sorry, don't remember the exact config I used

**Comment by Tocic** [comment]
Tested it again.
Linux 4.16.3, gcc 7.3.1, cmake 3.10, make 4.2.1.
With the following commands    
```
cmake -DCMAKE_INSTALL_PREFIX=/usr . \
          -DOPENSLIDE_INCLUDE_DIR=/usr/include/openslide/ \
          -DUNITTEST_INCLUDE_DIR=/usr/include/UnitTest++ \
          -DUNITTEST_LIBRARY=/usr/lib/libUnitTest++.a \
          -DUNITTEST_LIBRARY_DEBUG=/usr/lib/libUnitTest++.a \
          -DBUILD_DIAG_PATHOLOGY_EXECUTABLES=ON \
          -DBUILD_DIAG_PATHOLOGY_WORKSTATION=ON \
          -DBUILD_DIAG_PATHOLOGY_IMAGEPROCESSING=ON \
          -DBUILD_DIAG_PATHOLOGY_TESTS=ON \
          -DBUILD_DIAG_PATHOLOGY_INSTALL=ON

make
```
I've got the following errors:

> ASAP-1.7.4/imgproc/basicfilters/ColorDeconvolutionFilter.h:43:26: error: there are no arguments to ‘log’ that depend on a template parameter, so a declaration of 
‘log’ must be available
> ASAP-1.7.4/imgproc/basicfilters/ColorDeconvolutionFilter.h:112:23: error: there are no arguments to ‘sqrt’ that depend on a template parameter, so a declaration of 
‘sqrt’ must be available

and so on for `cmath` functions, because `g++` can't find their declarations. For example in a `ColorDeconvolutionFilter.h` file a `sqrt` function is not declared in `map, string, vector,  ImageFilter.h` implementation.

**Comment by GeertLitjens** [comment]
Think this is no longer needed, did not have any issues with the latest versions of Ubuntu/Visual Studio

**Pull request closed without merging**
